### ISSUE TITLE
[Reformat] Formatting of `not in` expressions is broken

### ISSUE THREAD

**Issue by freundTech** [jeffa5/typstfmt#30]
**To Reproduce**

Code snippet:

```typst
#if "a" not in ("b",) [
  abc
]
```

**Version**

Current HEAD (932271172123cbf46a932ec6a9769413c532be90)

**Additional context**
When formatting a `not in` expression typst removes the space between the first operand and the `not`. This is especially bad if the first operand is a variable as it will lead a typst file that doesn't compile because of a missing variable name.

**Comment by jeffa5** [comment]
This is because the Typst compiler currently parses the "not in" as two separate tokens, rather than one (https://github.com/typst/typst/issues/2649). I'll see if I can hack around it for now.
