### ISSUE TITLE
add option for stdin so this can be used within an editor?

### ISSUE THREAD

**Issue by sbromberger** [jeffa5/typstfmt#37]
Maybe I'm missing an option, but it would be great if `typstfmt` did inline rewriting - this way, we could invoke an editor's `format` action to get format-on-save or format-on-demand.

Thanks!

**Comment by jeffa5** [comment]
That seems like a sensible addition. I'd expect it to be the behaviour when there are no paths given, rather than I think the current way of finding all `.typ` files.

@sbromberger Was this mistakenly closed? I'll reopen for now as I think its valid still.
