### ISSUE TITLE
Integration with mason.nvim

### ISSUE THREAD

**Issue by Keithagy** [jeffa5/typstfmt#39]
Hello, would there be any interest for this project to be integrated into [mason.nvim](https://github.com/williamboman/mason.nvim) for easier management within a neovim config? I would be interested in taking a crack at it, if that is the case. Thank you!

**Comment by jeffa5** [comment]
I'm not sure if that would require anything in this repo? From a quick look it seems like it is best to integrate formatters with either https://github.com/mhartington/formatter.nvim or https://github.com/jose-elias-alvarez/null-ls.nvim
